### ISSUE TITLE
Why should I put javax.websocket-api into my pom.xml?

### ISSUE THREAD

**Issue by shabak** [g00glen00b/spring-ng-chat#2]
Hello! Thanks for this clear example! So, the question is in the header. I've tried to build and run without this dependency and it works...

**Comment by g00glen00b** [comment]
Well, in this case you don't need it, but as soon as you directly use a class from the Websocket API, then you'll have to add it as a runtime library to make sure it will compile locally. Once you deploy it you'll never need it, because it's provided by the webcontainer. That's why I added `<scope>provided</scope>`.
